# Generated by Django 4.2.3 on 2023-08-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='caver',
            new_name='cover',
        ),
    ]
